EvilDataUpload/Controllers/DataDisplayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using EvilDataUpload.Models;

namespace EvilDataUpload.Controllers
{
    public class DataDisplayController : Controller
    {
        public ActionResult DisplayData()
        {
            return View();
        }

        public async Task<ActionResult> LookupInsertedData(string userInput)
        {
           
            UserData rowDisplayResult = new UserData();
            if (!string.IsNullOrEmpty(userInput))
            {
                DataConnect connect = new DataConnect();
                rowDisplayResult = await connect.DownloadDataAsync(userInput);
            }

            return View("DisplayData", rowDisplayResult);
        }
    }
}

EvilDataUpload/Controllers/DataUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Newtonsoft.Json;
using EvilDataUpload.Models;
using System.Net;
using System.Threading.Tasks;

namespace EvilDataUpload.Controllers
{
    public class DataUploadController : AsyncController
    {
        public ActionResult UploadFile()
        {
            return View("UploadData");
        }

        [HttpPost]
        public async Task<ActionResult> UploadSubmittedFile(HttpPostedFileBase fileInput)
        {
            List<UserData> uploadedRowsList = new List<UserData>();
            
            if (fileInput != null && Path.GetExtension(fileInput.FileName).ToLower() == ".csv")
            {
                string fileContent = string.Empty;
                string tempResult = String.Empty;
                string line = string.Empty;
                int counterSent = 0;
                int counterTotal = 0;
                int counterUploadFailed = 0;
                string errors = string.Empty;

                using (StreamReader streamReader = new StreamReader(fileInput.InputStream))
                {
                    fileContent = streamReader.ReadToEnd();
                }

                string[] lines = fileContent.Split(new string[] { "\r\n", "\n", "\r" }, StringSplitOptions.RemoveEmptyEntries);
                
                if (lines.Length > 0)
                {
                    Guid uid = Guid.NewGuid();
                    for (int i = 0; i < lines.Length; i++)
                    {
                        UserData rowUploadResult = new UserData();
                        string[] lineValues = lines[i].Split(new char[] { ',' });
                        counterTotal++;
                        
                        if (lineValues.Length == 2 && (lineValues[0] != string.Empty || lineValues[1] != string.Empty))
                        {
                            uploadedRowsList.Add(rowUploadResult);

                            if(lineValues[0] == string.Empty)
                                rowUploadResult.Errors.Add("Error: the customer name is empty.");

                            int intValue = 0;
                            if (!Int32.TryParse(lineValues[1], out intValue))
                            {
                                rowUploadResult.Errors.Add("Error: the value is not numeric: " + lineValues[1]);

                                if (lineValues[0] == string.Empty)
                                    continue;
                            }

                            rowUploadResult.UploaderName = "Irina";
                            rowUploadResult.CustomerName = lineValues[0];
                            rowUploadResult.Action = "order created";
                            rowUploadResult.CustomerValue = intValue;
                            rowUploadResult.File = fileInput.FileName;
                             
                            DataConnect connect = new DataConnect();
                            rowUploadResult = await connect.SendUploadedDataAsync(rowUploadResult, counterSent);

                            if (rowUploadResult.Hash.Length != 32)
                            {
                                rowUploadResult.Hash = string.Empty;
                                rowUploadResult.Errors.Add("Error: invalid hash in server response.");
                            }

                            int dbUpdate = await connect.AddToDatabase(uid, rowUploadResult);
                            
                            if(rowUploadResult.UploadStatus == "false")
                                counterUploadFailed++;
                            
                            counterSent++;
                        }
                    }
                }
            }
            else
            {
                uploadedRowsList.Add(new UserData() { Errors = new List<string>() { "Please upload a .csv file" } });
            }

            return View("UploadData", uploadedRowsList);
        }
    }
}

EvilDataUpload/Views/Shared/DisplayData.cshtml
@model EvilDataUpload.Models.UserData

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Uploaded Data Lookup</title>
</head>
<body>
    <table>
        <tr>
            <td>@Html.ActionLink("File Upload", "UploadFile", "DataUpload")</td>
            <td>@Html.ActionLink("Search For Records", "DisplayData", "DataDisplay")</td>
        </tr>
    </table>
    <br><br>

@using (Html.BeginForm("LookupInsertedData", "DataDisplay", FormMethod.Get))
{
        <p>
        Provide hash to lookup data:
    </p>
    <table>
        <tr>
            <td><input type="text" id="userInputId" name="userInput" required></td>
            <td><input type="submit" value="Submit"></td>
        </tr>
    </table>
}
    <br>

@if(Model !=null)
{
    if(Model.Hash != null)
    { 
        <p><b>Result:</b></p>
        <table border="1" cellpadding="5" cellspacing="1" style="text-align:left">
            <tr>
                <th>Customer Name</th>
                <th>Customer Value</th>
                <th>File</th>
                <th>Hash</th>
                <th>Action</th>
                <th>Property</th>
            </tr>
            <tr>
                <td>@Model.CustomerName</td>
                <td>@Model.CustomerValue</td>
                <td>@Model.File</td>
                <td>@Model.Hash</td>
                <td>@Model.Action</td>
                <td>@Model.UploaderName</td>
            </tr>
        </table>
    }
    else
    {
        <ul>
            @if (Model.Errors.Count() > 0)
            {
                foreach (var error in Model.Errors)
                {
                    <li> @error </li>
                }
            }
        </ul>
    }
}
</body>
</html>

EvilDataUpload/Views/Shared/UploadData.cshtml
@model IEnumerable<EvilDataUpload.Models.UserData>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>File Upload</title>
</head>
<body>
    <table>
        <tr>
            <td>@Html.ActionLink("File Upload", "UploadFile", "DataUpload")</td>
            <td>@Html.ActionLink("Search For Records", "DisplayData", "DataDisplay")</td>
        </tr>
    </table>
    <br><br>

    @using (Html.BeginForm("UploadSubmittedFile", "DataUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        
        <table>
            <tr>
                <td>Upload File:</td>
                <td><input type="file" id="fileInput" name="fileInput" required></td>
                
            <tr>
                <td></td>
                <td><input type="submit" value="Submit"></td>
            </tr>
        </table>
    }
    <br>
   
    @if (Model != null && Model.Count() > 0)
    {
        <table border="1" cellpadding="5" cellspacing="1"  style="text-align:left">
            <tr>
                <th>Customer Name</th>
                <th>Customer Value</th>
                <th>File</th>
                <th>Hash</th>
                <th>Action</th>
                <th>Property</th>
                <th>Errors</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.CustomerName</td>
                    <td>@item.CustomerValue</td>
                    <td>@item.File</td>
                    <td>@item.Hash</td>
                    <td>@item.Action</td>
                    <td>@item.UploaderName</td>
                    <td>
                        <ul>
                            @foreach (var error in item.Errors)
                            {
                                <li> @error </li>
                            }
                        </ul>
                    </td>
                </tr>
            }
        </table>
    }
    
</body>
</html>